### ISSUE TITLE
VS2013 crashes when Web Essentials preview pane is used

### ISSUE THREAD

**Issue by jennings** [paulcbetts/SaveAllTheTime#42]
Save All The Time seems to be involved in a crash of Visual Studio 2013 in the following scenario:

1. Have Web Essentials 2013 installed with the TypeScript preview pane enabled.
2. Open a TypeScript file for editing. The preview pane appears.
3. Wait 2 seconds.

At this point, an unhandled exception takes down Visual Studio. I got the following exception details by debugging the crash, but not too much else. SaveAllTheTime is the only VS extension I have installed which uses ReactiveUI. I'm not too skilled at debugging Visual Studio extensions, but I'm more than happy to get more necessary information if I'm pointed in the right direction.

The crash is eliminated by either disabling SaveAllTheTime or by disabling the Web Essentials preview pane. But, I like having both of those things :cry: 

Outer exception which crashes VS:

> System.Exception
> An OnError occurred on an object (usually ObservableAsPropertyHelper) that would break a binding or command. To prevent this, Subscribe to the ThrownExceptions property of your objects

> Stack Trace:
```
   at ReactiveUI.RxApp.<>c__DisplayClass3.<.cctor>b__1()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass1`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

Inner exception:

> System.ArgumentException
> An entry with the same key already exists.

> Stack Trace:
```
   at System.Collections.Specialized.ListDictionary.Add(Object key, Object value)
   at System.Collections.Specialized.HybridDictionary.Add(Object key, Object value)
   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(Object key, Object property)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseSessionStackMapService.GetStackForTextView(ITextView textView)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.IsCompletionActive(ITextView textView)
   at SaveAllTheTime.DocumentMonitorService.<isCompletionActive>b__13(ITextView x)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at SaveAllTheTime.DocumentMonitorService.isCompletionActive()
   at SaveAllTheTime.DocumentMonitorService.<.ctor>b__0(Unit _)
   at System.Reactive.Linq.Observαble.Where`1._.OnNext(TSource value)
```

**Comment by paulcbetts** [comment]
I don't really use Visual Studio anymore and trying to upgrade this VSIX to be buildable has proven to be a nightmare. Sorry!
